version: '3.1'
services:
    anubis:
        build: .
        ports:
            - 9000:9000
        command: python anubis/serve.py
        tty: true
        stdin_open: true

    web1:
        image: strm/helloworld-http
        ports:
            - 8000:80
      
    web2:
        image: strm/helloworld-http
        ports:
            - 8001:80      

    web3:
        image: strm/helloworld-http
        ports:
            - 8002:80      
